//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------

// !!!! DO NOT EDIT THIS FILE WITH A NORMAL TEXT EDITOR !!!

// This file contains invalid UTF8 sequences that any sane editor would "fix".
// but would, however break this test. If you do edit it then make sure the invalid
// sequences are retained in the edited file before checking in.

function write(o1) {
    if (this.o2 == undefined) {
        o4.write(o1);
        o4.write("</br>");
    }
    else
        o2.o5(o1)
}

function test(o1, o7) {
  write(o1 == o7);
  var o8 = "result = \"" + o1 + "\"";
  eval(o8);
  write(o1 == o10);
}
  
// String containing invalid sequence C0 20 should be equivient to \uFFFD\u00020"
var o11 = "� ";
var o12 = "\uFFFD\u0020";
test(o11, o12);

// Ensure a valid sequence gets translated correctly.
var o13 = "ȅ";
var o14 = "\u0205";
test(o13, o14);

// Ensure surrogate pairs are encoded correctly
var o15 = "𐐀";
var o16 = "\uD801\uDC00";
test(o15, o16);

// Ensure invalid surrogate pairs are replaced with replacement characters.
var o17 = "��";
var o18 = "\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD";
test(o17, o18);

// Ensure invalid characters are not replaced with replacement characters.
var o19 = "￿";
var o20 = "\uFFFF";
test(o19, o20);
